import math

WIDTH = 1280
HEIGHT = 720
FPS = 60
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 240
MAX_DEPTH = 20
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
SCALE = WIDTH // NUM_RAYS

PLAYER_SPEED = 5.0
PLAYER_ROT_SPEED = 0.003
PLAYER_HEIGHT = 0.5
